# Generated by Django 5.0.9 on 2024-12-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('main_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_relationship', to='dcim.interface')),
                ('rx_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rx_relationship', to='dcim.interface')),
                ('tx_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tx_relationship', to='dcim.interface')),
            ],
        ),
    ]
